### ISSUE TITLE
It doesn't launch on mac OS

### ISSUE THREAD

**Issue by t-cool** [vlad-km/moren-electron#6]
@vlad-km 
I use mac OS.

```
$ cd repl
$ npm install
$ npm start 
   or 
$ electron .
```
After setting up, the electron window comes up, but the screen is black...

Could you give me some advise?

I'd appreciate your help.

**Comment by vlad-km** [comment]
I added some components.
Please see latest update on git.
Try this update.

**Comment by t-cool** [comment]
thank you for your update!
I tried again, but the situation was the same...

$ cd /Users/noguchihiroki/Desktop/moren-electron-master/repl/
$ npm install

> electron@1.7.10 postinstall /Users/noguchihiroki/Desktop/moren-electron-master/repl/node_modules/electron
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN Moren@1.0.1 No repository field.

added 152 packages in 8.286s
$ npm start

> Moren@1.0.1 start /Users/noguchihiroki/Desktop/moren-electron-master/repl
> electron esmd.js

=> black electron screen ...

**Comment by vlad-km** [comment]
Please see fixed repl/package.json
What to do:
1.  del node_modules  from /Users/noguchihiroki/Desktop/moren-electron-master/repl
2.  npm install
3.  npm start
If again black screen, press Ctrl-Shift-I, the window devtolols will open. Please copy messages from console.

**Comment by vlad-km** [comment]
Please update repl/sys from git.

After the Moren started, the console will display messages:
```
boot package ./sys/view not exists
boot package ./sys/msc not exists
```
Ignore them.

**Comment by t-cool** [comment]
@vlad-km 
Thank you for your advice!!
It works!!

**Comment by vlad-km** [comment]
I'm glad that helped you.
